name: pull request linter

on:
  push:
    branches: [ "main" ]
env:
  SOURCE_FOLDER: src
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  run-selene-linter:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Selene
        run: cargo install selene
      - name: Selene
        run: selene $SOURCE_FOLDER
