name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ls
      - run: sudo apt install zip # bosta precisa ser SUDO pra usar isso
      - run: zip archivename .* * linguica.zip
# mijei
